name: wm_website
description: WeMultiply Marketing Website
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.1
  jaspr_router: ^0.8.1
  http: ^1.2.0

dev_dependencies:
  jaspr_tailwind: ^0.3.0
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.9
  jaspr_builder: ^0.22.1
  lints: ^5.0.0

jaspr:
  mode: server
